// The ruleset text. Generated by upstream's own shared builder (vendored), so
// the injected text is identical to upstream's for every level.
import { createRequire } from "node:module"
import { UPSTREAM_INSTRUCTIONS } from "./paths.js"

const require = createRequire(import.meta.url)
const upstream = require(UPSTREAM_INSTRUCTIONS)

export const getPonytailInstructions = upstream.getPonytailInstructions

// Upstream's V1 transform injects nothing for "off" and sends every other
// persisted level (including the cross-host "review" level) through the
// shared builder.
export function instructionsForMode(mode) {
  if (mode === "off") return null
  return getPonytailInstructions(mode)
}
